const mongoose = require('mongoose');
const s = new mongoose.Schema({
  _id:              { type:String },
  caterer_id:       { type:String, required:true },
  school_id:        { type:String },
  district_id:      { type:String },
  region_id:        { type:String },
  period:           { type:String },
  meals_served:     { type:Number, default:0 },
  days_covered:     { type:Number, default:0 },
  days_paid:        { type:Number, default:0 },
  days_arrears:     { type:Number, default:0 },
  rate_per_student: { type:Number, default:2.00 },
  amount_paid:      { type:Number, default:0 },
  arrears_amount:   { type:Number, default:0 },
  status:           { type:String,
    enum:['partial','fully-paid','pending_district','pending_regional','pending_national','approved','rejected'],
    default:'partial' },
  district_finance_approved:    { type:Boolean, default:false },
  district_finance_approved_by: { type:String },
  district_finance_approved_at: { type:Date },
  district_finance_days:        { type:Number },
  district_finance_comment:     { type:String },
  regional_finance_approved:    { type:Boolean, default:false },
  regional_finance_approved_by: { type:String },
  regional_finance_approved_at: { type:Date },
  regional_finance_comment:     { type:String },
  national_finance_approved:    { type:Boolean, default:false },
  national_finance_approved_by: { type:String },
  national_finance_approved_at: { type:Date },
  national_finance_comment:     { type:String },
  last_payment_date: { type:String },
  source:            { type:String },
  reference:         { type:String },
  caterer_reported:  { type:Boolean, default:false },
  received_amount:   { type:Number, default:0 },
  visible_to_caterer:{ type:Boolean, default:false },
  created_at:        { type:Date, default:Date.now },
},{ _id:false });
module.exports = mongoose.models.Payment || mongoose.model('Payment', s);
